SELECT ID,
CASE
    WHEN PR <= 0.25 THEN 'CRITICAL'
    WHEN PR <= 0.5 THEN 'HIGH'
    WHEN PR <= 0.75 THEN 'MEDIUM'
    WHEN PR <= 1 THEN 'LOW'
END AS COLONY_NAME
FROM (
    SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PR
    FROM ECOLI_DATA
    ORDER BY 1
) AS PR_DATA